version: '3.8'
services:
  wso2is:
    image: docker.wso2.com/wso2is:5.11.0
    container_name: wso2is
    ports:
      - "9444:9444"
    environment:
      - WAIT_FOR_PORT=9444
    volumes:
      - ./poc:/home/wso2is-5.11.0/poc
    entrypoint: /home/wso2is-5.11.0/poc/entrypoint.sh

networks:
  wso2-network:
    external: true