version: '3.8'
services:
  wso2is:
    image: docker.wso2.com/wso2is:5.11.0
    container_name: wso2is
    ports:
      - "9443:9443"
    environment:
      - WAIT_FOR_PORT=9443
    volumes:
      - ./repository/deployment/server:/home/wso2carbon/wso2is-5.11.0/repository/deployment/server
      - ./repository/conf:/home/wso2carbon/wso2is-5.11.0/repository/conf

networks:
  wso2-network:
    driver: bridge