version: '3.8'
services:
  wso2am:
    image: docker.wso2.com/wso2am:4.0.0
    container_name: wso2am
    ports:
      - "9443:9443"
      - "9763:9763"
      - "8243:8243"
      - "8280:8280"
    environment:
      - WAIT_FOR_PORT=9443
    volumes:
      - ./repository/deployment/server:/home/wso2carbon/wso2am-4.0.0/repository/deployment/server
      - ./repository/conf:/home/wso2carbon/wso2am-4.0.0/repository/conf

networks:
  wso2-network:
    driver: bridge